kind: PersistentVolume
apiVersion: v1

metadata:
  name: mssql-pv
  namespace: dotnet-ns

spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mssql
    