kind: Deployment
apiVersion: apps/v1

metadata:
  name: mssql
  namespace: dotnet-ns
  labels:
    app: sql

spec:
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql

    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
        - containerPort: 1433

        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_PID
          value: "Developer"
        - name: MSSQL_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        volumeMounts:
        - name: mssql-storage
          mountPath: /var/opt/mssql
      
      volumes:
      - name: mssql-storage
        emptyDir: {}


